import 'package:basic_project/core/extensions/context_extension.dart';
import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';

class TextStylesRes {
  final BuildContext context;

  const TextStylesRes( this.context);

  TextStyle _base({
    required FontWeight fontWeight,
    double fontSize = 16,
    Color? color,
    String? fontFamily,
    List<String>? fontFamilyFallback,
    FontStyle? fontStyle,
    double? letterSpacing,
    double? wordSpacing,
    double? height,
    TextBaseline? textBaseline,
    TextDecoration? decoration,
    Color? decorationColor,
    TextDecorationStyle? decorationStyle,
    double? decorationThickness,
    Paint? foreground,
    Paint? background,
    Color? backgroundColor,
    List<Shadow>? shadows,
    List<FontFeature>? fontFeatures,
    List<FontVariation>? fontVariations,
    TextOverflow? overflow,
    String? debugLabel,
  }) =>
      TextStyle(
        fontSize: fontSize.sp,
        fontWeight: fontWeight,
        color: foreground == null ? (color ?? context.colors.primary) : null,
        fontFamily: fontFamily,
        fontFamilyFallback: fontFamilyFallback,
        fontStyle: fontStyle,
        letterSpacing: letterSpacing,
        wordSpacing: wordSpacing,
        height: height,
        textBaseline: textBaseline,
        decoration: decoration,
        decorationColor: decorationColor,
        decorationStyle: decorationStyle,
        decorationThickness: decorationThickness,
        foreground: foreground,
        background: background,
        backgroundColor: backgroundColor,
        shadows: shadows,
        fontFeatures: fontFeatures,
        fontVariations: fontVariations,
        overflow: overflow,
        debugLabel: debugLabel,
      );

  TextStyle regularStyle({
    Color? color,
    double fontSize = 16,
    String? fontFamily,
    List<String>? fontFamilyFallback,
    FontStyle? fontStyle,
    double? letterSpacing,
    double? wordSpacing,
    double? height,
    TextBaseline? textBaseline,
    TextDecoration? decoration,
    Color? decorationColor,
    TextDecorationStyle? decorationStyle,
    double? decorationThickness,
    Paint? foreground,
    Paint? background,
    Color? backgroundColor,
    List<Shadow>? shadows,
    List<FontFeature>? fontFeatures,
    List<FontVariation>? fontVariations,
    TextOverflow? overflow,
    String? debugLabel,
  }) =>
      _base(
        fontWeight: FontWeight.w400,
        fontSize: fontSize,
        color: color,
        fontFamily: fontFamily,
        fontFamilyFallback: fontFamilyFallback,
        fontStyle: fontStyle,
        letterSpacing: letterSpacing,
        wordSpacing: wordSpacing,
        height: height,
        textBaseline: textBaseline,
        decoration: decoration,
        decorationColor: decorationColor,
        decorationStyle: decorationStyle,
        decorationThickness: decorationThickness,
        foreground: foreground,
        background: background,
        backgroundColor: backgroundColor,
        shadows: shadows,
        fontFeatures: fontFeatures,
        fontVariations: fontVariations,
        overflow: overflow,
        debugLabel: debugLabel,
      );

  TextStyle mediumStyle({
    Color? color,
    double fontSize = 16,
    String? fontFamily,
    List<String>? fontFamilyFallback,
    FontStyle? fontStyle,
    double? letterSpacing,
    double? wordSpacing,
    double? height,
    TextBaseline? textBaseline,
    TextDecoration? decoration,
    Color? decorationColor,
    TextDecorationStyle? decorationStyle,
    double? decorationThickness,
    Paint? foreground,
    Paint? background,
    Color? backgroundColor,
    List<Shadow>? shadows,
    List<FontFeature>? fontFeatures,
    List<FontVariation>? fontVariations,
    TextOverflow? overflow,
    String? debugLabel,
  }) =>
      _base(
        fontWeight: FontWeight.w500,
        fontSize: fontSize,
        color: color,
        fontFamily: fontFamily,
        fontFamilyFallback: fontFamilyFallback,
        fontStyle: fontStyle,
        letterSpacing: letterSpacing,
        wordSpacing: wordSpacing,
        height: height,
        textBaseline: textBaseline,
        decoration: decoration,
        decorationColor: decorationColor,
        decorationStyle: decorationStyle,
        decorationThickness: decorationThickness,
        foreground: foreground,
        background: background,
        backgroundColor: backgroundColor,
        shadows: shadows,
        fontFeatures: fontFeatures,
        fontVariations: fontVariations,
        overflow: overflow,
        debugLabel: debugLabel,
      );

  TextStyle boldStyle({
    Color? color,
    double fontSize = 16,
    String? fontFamily,
    List<String>? fontFamilyFallback,
    FontStyle? fontStyle,
    double? letterSpacing,
    double? wordSpacing,
    double? height,
    TextBaseline? textBaseline,
    TextDecoration? decoration,
    Color? decorationColor,
    TextDecorationStyle? decorationStyle,
    double? decorationThickness,
    Paint? foreground,
    Paint? background,
    Color? backgroundColor,
    List<Shadow>? shadows,
    List<FontFeature>? fontFeatures,
    List<FontVariation>? fontVariations,
    TextOverflow? overflow,
    String? debugLabel,
  }) =>
      _base(
        fontWeight: FontWeight.w700,
        fontSize: fontSize,
        color: color,
        fontFamily: fontFamily,
        fontFamilyFallback: fontFamilyFallback,
        fontStyle: fontStyle,
        letterSpacing: letterSpacing,
        wordSpacing: wordSpacing,
        height: height,
        textBaseline: textBaseline,
        decoration: decoration,
        decorationColor: decorationColor,
        decorationStyle: decorationStyle,
        decorationThickness: decorationThickness,
        foreground: foreground,
        background: background,
        backgroundColor: backgroundColor,
        shadows: shadows,
        fontFeatures: fontFeatures,
        fontVariations: fontVariations,
        overflow: overflow,
        debugLabel: debugLabel,
      );

  TextStyle semiBoldStyle({
    Color? color,
    double fontSize = 16,
    String? fontFamily,
    List<String>? fontFamilyFallback,
    FontStyle? fontStyle,
    double? letterSpacing,
    double? wordSpacing,
    double? height,
    TextBaseline? textBaseline,
    TextDecoration? decoration,
    Color? decorationColor,
    TextDecorationStyle? decorationStyle,
    double? decorationThickness,
    Paint? foreground,
    Paint? background,
    Color? backgroundColor,
    List<Shadow>? shadows,
    List<FontFeature>? fontFeatures,
    List<FontVariation>? fontVariations,
    TextOverflow? overflow,
    String? debugLabel,
  }) =>
      _base(
        fontWeight: FontWeight.w600,
        fontSize: fontSize,
        color: color,
        fontFamily: fontFamily,
        fontFamilyFallback: fontFamilyFallback,
        fontStyle: fontStyle,
        letterSpacing: letterSpacing,
        wordSpacing: wordSpacing,
        height: height,
        textBaseline: textBaseline,
        decoration: decoration,
        decorationColor: decorationColor,
        decorationStyle: decorationStyle,
        decorationThickness: decorationThickness,
        foreground: foreground,
        background: background,
        backgroundColor: backgroundColor,
        shadows: shadows,
        fontFeatures: fontFeatures,
        fontVariations: fontVariations,
        overflow: overflow,
        debugLabel: debugLabel,
      );

  TextStyle lightStyle({
    Color? color,
    double fontSize = 16,
    String? fontFamily,
    List<String>? fontFamilyFallback,
    FontStyle? fontStyle,
    double? letterSpacing,
    double? wordSpacing,
    double? height,
    TextBaseline? textBaseline,
    TextDecoration? decoration,
    Color? decorationColor,
    TextDecorationStyle? decorationStyle,
    double? decorationThickness,
    Paint? foreground,
    Paint? background,
    Color? backgroundColor,
    List<Shadow>? shadows,
    List<FontFeature>? fontFeatures,
    List<FontVariation>? fontVariations,
    TextOverflow? overflow,
    String? debugLabel,
  }) =>
      _base(
        fontWeight: FontWeight.w300,
        fontSize: fontSize,
        color: color,
        fontFamily: fontFamily,
        fontFamilyFallback: fontFamilyFallback,
        fontStyle: fontStyle,
        letterSpacing: letterSpacing,
        wordSpacing: wordSpacing,
        height: height,
        textBaseline: textBaseline,
        decoration: decoration,
        decorationColor: decorationColor,
        decorationStyle: decorationStyle,
        decorationThickness: decorationThickness,
        foreground: foreground,
        background: background,
        backgroundColor: backgroundColor,
        shadows: shadows,
        fontFeatures: fontFeatures,
        fontVariations: fontVariations,
        overflow: overflow,
        debugLabel: debugLabel,
      );

}

